// ─── Kivara Luxury Travel ──────────────────────────────────────────────
// Africa's most coveted romance sanctuary.
// We occupy the space between Aman's serenity and &Beyond's wilderness.
// ──────────────────────────────────────────────────────────────────────

// ─── UNSplash Image Library ───────────────────────────────────────────
// Cinematic imagery sourced for each destination and property

export const IMAGES = {
  // Lake Malawi
  lakeMalawiHero: "/images/lake-malawi-hero.jpg",
  lakeMalawiAerial: "/images/lake-malawi-aerial.jpg",
  lakeMalawiSunset: "/images/lake-malawi-sunset.jpg",
  lakeMalawiBeach: "/images/lake-malawi-beach.jpg",
  lakeMalawiDhow: "/images/lake-malawi-dhow.jpg",
  lakeMalawiIsland: "/images/lake-malawi-island.jpg",

  // South Luangwa
  southLuangwaHero: "/images/south-luangwa-hero.jpg",
  southLuangwaElephant: "/images/south-luangwa-elephant.jpg",
  southLuangwaLeopard: "/images/south-luangwa-leopard.jpg",
  southLuangwaSunset: "/images/south-luangwa-sunset.jpg",
  southLuangwaSafari: "/images/south-luangwa-safari.jpg",
  southLuangwaCamp: "/images/south-luangwa-camp.jpg",

  // Zanzibar
  zanzibarHero: "/images/zanzibar-hero.jpg",
  zanzibarBeach: "/images/zanzibar-beach.jpg",
  zanzibarAerial: "/images/zanzibar-aerial.jpg",
  zanzibarDhow: "/images/zanzibar-dhow.jpg",
  zanzibarSpa: "/images/zanzibar-spa.jpg",
  zanzibarStoneTown: "/images/zanzibar-stonetown.jpg",

  // Properties
  kayaMawa: "/images/kaya-mawa.jpg",
  pumulani: "/images/pumulani.jpg",
  blueZebra: "/images/blue-zebra.jpg",
  chinzombo: "/images/chinzombo.jpg",
  pukuRidge: "/images/puku-ridge.jpg",
  shawaLuangwa: "/images/shawa-luangwa.jpg",
  luangwaRiver: "/images/luangwa-river.jpg",
  xanadu: "/images/xanadu.jpg",
  whiteSand: "/images/white-sand.jpg",
  residence: "/images/residence.jpg",

  // Experiences
  dining: "/images/dining.jpg",
  walking: "/images/walking.jpg",
  dhow: "/images/dhow.jpg",
  spa: "/images/spa.jpg",
  starbed: "/images/starbed.jpg",
  bushDining: "/images/bush-dining.jpg",

  // Journal
  journalHoneymoon: "/images/journal-honeymoon.jpg",
  journalMalawi: "/images/journal-malawi.jpg",
  journalWalking: "/images/journal-walking.jpg",
  journalZanzibar: "/images/journal-zanzibar.jpg",

  // Hero video poster frames
  heroPoster: "/images/hero-poster.jpg",
} as const;

export const BRAND_POSITIONING = {
  tagline: "Where the Soul of the Bush Meets the Serenity of the Shore.",
  description:
    "A handcrafted collection of Africa's most exquisite beach and bush escapes. Curated exclusively for couples who refuse to compromise on beauty, intimacy, or refinement.",
  betweenAmanAndBeyond:
    "We occupy the space between Aman's serenity and &Beyond's wilderness. Like Aman, we worship space and silence. Like &Beyond, we honor the raw and the wild. We are Kivara: Africa's most romantic gateway.",
  storyBrand: {
    hero: "You. A couple in love. A partnership that deserves celebrating.",
    problem: "Most vacations distract. You deserve a journey that deepens your connection.",
    guide: "Kivara. Your personal curators of romance. We know Africa's most secret gardens, its most intimate camps, its most soul-stirring shorelines.",
    plan: "A bespoke journey around your love story. Three destinations. Nine extraordinary properties. Infinite moments of wonder.",
    callToAction: "Begin Your Journey.",
    success: "You return transformed. Closer. More in love. Africa stays with you forever.",
    stakes: "Settle for ordinary, and Africa's magic stays someone else's story. The golden light over Luangwa. The silence of a Lake Malawi sunrise. The scent of cloves in Zanzibar's twilight. These are yours for the taking.",
  },
};

export const SITE_CONFIG = {
  name: "Kivara",
  tagline: BRAND_POSITIONING.tagline,
  description: BRAND_POSITIONING.description,
  url: "https://kivara.luxury",
  email: "concierge@kivara.luxury",
  phone: "+27 87 123 4567",
  whatsapp: "+27871234567",
  social: {
    instagram: "https://instagram.com/kivara",
    tiktok: "https://tiktok.com/@kivara",
    facebook: "https://facebook.com/kivara",
    pinterest: "https://pinterest.com/kivara",
  },
};

export const BRAND = {
  colors: {
    sand: "#D4C5A9",
    sandLight: "#E8DCC8",
    sandDark: "#B8A88A",
    warmWhite: "#F5F0EB",
    warmWhiteDark: "#EDE5DA",
    softBlack: "#1A1A1A",
    softBlackLight: "#2C2C2C",
    earth: "#8B7D6B",
    earthLight: "#A89880",
    gold: "#C9A96E",
    goldLight: "#D4BC8A",
    goldDark: "#B8944A",
    cream: "#FAF7F2",
  },
  fonts: {
    heading: "'Trajan Pro', 'Cinzel', 'Cormorant Garamond', serif",
    body: "'Montserrat', 'Inter', 'Helvetica Neue', Arial, sans-serif",
  },
};

export const DESTINATIONS = [
  {
    id: "lake-malawi",
    title: "Lake Malawi",
    subtitle: "Africa's Best Kept Secret. Your Private Freshwater Paradise.",
    tagline: "Where the lake becomes an ocean of tranquility",
    description:
      "Lake Malawi. Africa's third largest lake holds crystal waters, shores untouched by time, and an atmosphere of such profound serenity that couples find themselves speaking in whispers.",
    positioning:
      "Horizon of water and sky. Kayak at dawn. Dine beneath constellations on a private beach. Kaya Mawa, Pumulani, and Blue Zebra Island Lodge each write their own chapter of this love story. Africa's hidden luxury beach escape. Reserved for those who know where to look.",
    heroImage: IMAGES.lakeMalawiHero,
    slug: "lake-malawi",
    properties: ["kaya-mawa", "pumulani-lodge", "blue-zebra-island-lodge"],
    experiences: [
      "Private beach dining beneath a canopy of stars",
      "Sunset dhow cruises across the Lake of Stars",
      "Snorkeling in crystalline freshwater coves",
      "Private picnics on deserted islands",
      "Kayaking through golden hour light",
      "Intimate cultural encounters with lakeside villages",
    ],
    seasons: {
      bestTime: "April to October",
      closed: "Some properties close November to March due to rainy season",
      months: [
        { name: "January", temp: "26°C", weather: "Hot, occasional rain", open: true },
        { name: "February", temp: "26°C", weather: "Hot, occasional rain", open: true },
        { name: "March", temp: "26°C", weather: "Rainy season ends", open: true },
        { name: "April", temp: "25°C", weather: "Dry season begins", open: true },
        { name: "May", temp: "24°C", weather: "Perfect weather", open: true },
        { name: "June", temp: "22°C", weather: "Ideal conditions", open: true },
        { name: "July", temp: "21°C", weather: "Peak season", open: true },
        { name: "August", temp: "22°C", weather: "Peak season", open: true },
        { name: "September", temp: "24°C", weather: "Excellent", open: true },
        { name: "October", temp: "25°C", weather: "Great weather", open: true },
        { name: "November", temp: "26°C", weather: "Rain begins", open: "partial" },
        { name: "December", temp: "26°C", weather: "Rainy season", open: "partial" },
      ],
    },
  },
  {
    id: "south-luangwa",
    title: "South Luangwa",
    subtitle: "The Birthplace of the Walking Safari. The Soul of African Wilderness.",
    tagline: "Where intimacy with the wild transforms you",
    description:
      "South Luangwa. The birthplace of the walking safari. An unfiltered communion with the natural world that strips away everything unnecessary and leaves only what matters.",
    positioning:
      "Africa as it was before fences, before crowds, before compromise. Here, luxury means falling asleep to the rumble of lions and waking to the call of fish eagles. Four extraordinary properties — Time+Tide Chinzombo, Puku Ridge Camp, Shawa Luangwa Camp, and Luangwa River Camp — each offers a different window into this ancient world. From award-winning riverside villas to silent electric safaris, this is safari luxury for those who seek not just to see Africa but to feel it.",
    heroImage: IMAGES.southLuangwaHero,
    slug: "south-luangwa",
    properties: ["chinzombo", "puku-ridge-camp", "shawa-luangwa", "luangwa-river-camp"],
    experiences: [
      "Guided walking safaris following ancient elephant paths",
      "Night drives revealing the bush after dark",
      "Sundowners on the riverbank as Africa paints the sky",
      "Bush breakfasts where zebras are your dining companions",
      "Exclusive photography hides for intimate wildlife encounters",
      "Stargazing from raised platforms above the floodplain",
    ],
    seasons: {
      bestTime: "April to October",
      closed: "Most properties close November to March due to wet season and road conditions",
      months: [
        { name: "January", temp: "28°C", weather: "Wet season", open: false },
        { name: "February", temp: "28°C", weather: "Wet season", open: false },
        { name: "March", temp: "27°C", weather: "Wet season ends", open: false },
        { name: "April", temp: "26°C", weather: "Dry season begins", open: true },
        { name: "May", temp: "24°C", weather: "Excellent weather", open: true },
        { name: "June", temp: "22°C", weather: "Peak season", open: true },
        { name: "July", temp: "21°C", weather: "Peak season", open: true },
        { name: "August", temp: "22°C", weather: "Peak season", open: true },
        { name: "September", temp: "25°C", weather: "Excellent", open: true },
        { name: "October", temp: "27°C", weather: "Great weather", open: true },
        { name: "November", temp: "28°C", weather: "Rain begins", open: false },
        { name: "December", temp: "28°C", weather: "Wet season", open: false },
      ],
    },
  },
  {
    id: "zanzibar",
    title: "Zanzibar",
    subtitle: "The Spice Island. The Apex of Tropical Romance.",
    tagline: "Where history, spice, and turquoise waters converge",
    description:
      "Zanzibar. A love letter written in cinnamon and clove. Stone Town alleyways lead to beaches of impossible beauty. The Indian Ocean trades in shades of turquoise no artist could replicate.",
    positioning:
      "Culture and paradise intertwined. Spice-scented corridors, dhows sailing into fiery sunsets, and three extraordinary properties — Xanadu Villas, Zanzibar White Sand Villas, The Residence Zanzibar — each a sanctuary of romance. Tropical elegance, refined to perfection.",
    heroImage: IMAGES.zanzibarHero,
    slug: "zanzibar",
    properties: ["xanadu-villas", "zanzibar-white-sand-villas", "the-residence-zanzibar"],
    experiences: [
      "Spice plantation tours through ancient aromatic gardens",
      "Stone Town heritage walks through living history",
      "Private sandbank dining surrounded by the Indian Ocean",
      "Sunset dhow cruises with champagne and Swahili canapes",
      "Couples spa rituals using indigenous Zanzibari ingredients",
      "Deep sea fishing expeditions into the Indian Ocean",
    ],
    seasons: {
      bestTime: "June to October, December to February",
      closed: "Open year-round - occasional short rains in November and April/May",
      months: [
        { name: "January", temp: "27°C", weather: "Peak dry season", open: true },
        { name: "February", temp: "28°C", weather: "Peak dry season", open: true },
        { name: "March", temp: "28°C", weather: "Dry season", open: true },
        { name: "April", temp: "27°C", weather: "Short rains", open: true },
        { name: "May", temp: "26°C", weather: "Short rains", open: true },
        { name: "June", temp: "25°C", weather: "Dry season begins", open: true },
        { name: "July", temp: "24°C", weather: "Peak season", open: true },
        { name: "August", temp: "24°C", weather: "Peak season", open: true },
        { name: "September", temp: "25°C", weather: "Excellent", open: true },
        { name: "October", temp: "26°C", weather: "Great weather", open: true },
        { name: "November", temp: "27°C", weather: "Short rains", open: true },
        { name: "December", temp: "27°C", weather: "Dry season begins", open: true },
      ],
    },
  },
];

export const PROPERTIES = [
  {
    id: "kaya-mawa",
    name: "Kaya Mawa",
    destination: "lake-malawi",
    location: "Likoma Island, Lake Malawi",
    tagline: "Barefoot luxury on a private island sanctuary",
    description:
      "Perched on the shores of Likoma Island, Kaya Mawa is the apotheosis of barefoot luxury. Each suite handcrafted from local stone and thatch, opening to panoramic views of Lake Malawi's crystalline waters. A place where time suspends and love deepens.",
    longDescription:
      "Kaya Mawa is not a lodge. It is a sanctuary on one of Africa's most beautiful islands, built into the rocky shoreline with such reverence that the landscape remains the protagonist. Each of the ten suites and villas offers complete privacy with sweeping lake views, designed in a philosophy of minimal intervention: local stone, handwoven textiles, and an architecture that lets the water take center stage. Days unfold at nature's pace. Swim in the infinity pool that merges with the lake. Explore hidden coves by kayak. Lose yourself in a novel on your private deck while the lake whispers below. The restaurant serves farm to table cuisine with a Malawian soul. The bar perches over the water for sundowners that linger into starlit evenings. This is not a stay. This is a homecoming.",
    heroImage: IMAGES.kayaMawa,
    gallery: [IMAGES.lakeMalawiHero, IMAGES.lakeMalawiSunset, IMAGES.lakeMalawiBeach, IMAGES.lakeMalawiIsland],
    priceRange: "$650 to $1,200 per night",
    roomTypes: ["Lake View Suite", "Beach Villa", "Island House"],
    amenities: [
      "Private infinity pool",
      "Overwater bar",
      "Farm to table restaurant",
      "Private beach",
      "Kayaking and water sports",
      "Spa treatments",
      "Helicopter pad",
      "Complimentary WiFi",
    ],
    rating: 4.9,
    reviews: [
      { name: "Sarah and James Mitchell", text: "The most romantic place we have ever stayed. Every detail was perfection. We left a piece of our hearts on Likoma Island.", location: "London, United Kingdom" },
      { name: "Emma and Thomas Chen", text: "Kaya Mawa is pure magic. We arrived as guests and left as family. The Lake of Stars is real and it will change you.", location: "Sydney, Australia" },
    ],
    romanticHighlights: [
      "Private beach dinners beneath the Southern Cross",
      "Sunset dhow cruises across the Lake of Stars",
      "Couples massage on your private deck overlooking the lake",
      "Stargazing from your suite with nothing but the sound of water",
    ],
  },
  {
    id: "pumulani-lodge",
    name: "Pumulani Lodge",
    destination: "lake-malawi",
    location: "Nankoma Peninsula, Lake Malawi",
    tagline: "Where the lake meets the sky in perfect stillness",
    description:
      "Set on a private peninsula, Pumulani Lodge offers ten secluded villas with breathtaking views across Lake Malawi. A place of serene beauty and understated elegance where couples rediscover each other.",
    longDescription:
      "Pumulani Lodge occupies a pristine peninsula, offering a level of seclusion that feels like your own private world. The ten villas embody a contemporary African aesthetic: clean architectural lines, natural materials, and floor to ceiling windows that frame the lake as living art. Each villa features its own plunge pool and outdoor shower, creating an indoor outdoor living experience that dissolves the boundary between luxury and nature. The main lodge houses a stunning infinity pool, a curated library, and a dining room where the seasonal menu celebrates the flavors of Malawi with a sophistication that rivals the world's finest restaurants.",
    heroImage: IMAGES.pumulani,
    gallery: [IMAGES.lakeMalawiSunset, IMAGES.lakeMalawiBeach, IMAGES.lakeMalawiAerial],
    priceRange: "$550 to $1,000 per night",
    roomTypes: ["Lake View Villa", "Premium Villa", "Family Villa"],
    amenities: [
      "Private plunge pool",
      "Infinity pool overlooking the lake",
      "Outdoor shower",
      "Restaurant and bar",
      "Water sports equipment",
      "Spa sanctuary",
      "Curated library",
      "Complimentary WiFi",
    ],
    rating: 4.8,
    reviews: [
      { name: "Michael and Anna Barnes", text: "Paradise found. The villa, the views, the service extraordinary. We have traveled the world. This is different.", location: "New York, USA" },
    ],
    romanticHighlights: [
      "Private villa dining with your personal chef",
      "Couples spa journeys using indigenous ingredients",
      "Sunset cruises on the lake",
      "Secluded beach picnics on private coves",
    ],
  },
  {
    id: "blue-zebra-island-lodge",
    name: "Blue Zebra Island Lodge",
    destination: "lake-malawi",
    location: "Mumbo Island, Lake Malawi",
    tagline: "An island of your own in the Lake of Stars",
    description:
      "Exclusively set on a private island, Blue Zebra Island Lodge offers an intimate escape with pristine beaches and some of the finest freshwater snorkeling in Africa.",
    longDescription:
      "Blue Zebra Island Lodge occupies its own private island in the crystalline waters of Lake Malawi. With just ten rooms, the lodge offers an intimacy increasingly rare in travel. The island is a sanctuary for birdlife; the surrounding waters are a haven for snorkelers and divers exploring one of the world's most biodiverse freshwater ecosystems. Accommodation is understated, comfortable, and sustainable. Days are spent exploring the island's coves, swimming in the impossibly clear lake, or simply swaying in a hammock with the sound of lapping water as your only companion.",
    heroImage: IMAGES.blueZebra,
    gallery: [IMAGES.lakeMalawiIsland, IMAGES.lakeMalawiBeach, IMAGES.lakeMalawiAerial],
    priceRange: "$400 to $750 per night",
    roomTypes: ["Island Room", "Lake Front Suite", "Private House"],
    amenities: [
      "Private island experience",
      "Snorkeling gear and dive equipment",
      "Restaurant and bar",
      "Beach loungers and hammocks",
      "Bird watching guides",
      "Kayaking and paddleboarding",
      "Sundeck with panoramic views",
    ],
    rating: 4.7,
    reviews: [
      { name: "David and Claire Mueller", text: "An island paradise. The snorkeling was world class and the staff made us feel like the only people on earth.", location: "Berlin, Germany" },
    ],
    romanticHighlights: [
      "Exclusive island exploration for two",
      "Snorkeling in crystal clear coves hand in hand",
      "Private beachfront dining under the stars",
      "Sunset walks around your private island",
    ],
  },
  {
    id: "chinzombo",
    name: "Time + Tide Chinzombo",
    destination: "south-luangwa",
    location: "South Luangwa National Park, Zambia",
    tagline: "The ultimate in wild luxury at Zambia's premier safari camp",
    description:
      "Set on a sweeping curve of the Luangwa River within 60 acres of private land, Time+Tide Chinzombo brings award-winning style and sophistication to the Luangwa Valley. Six luxurious villas, each with a private plunge pool, redefine the boundaries of bush luxury.",
    longDescription:
      "Named after a type of tree which grows near camp, Time+Tide Chinzombo's natural building materials and vintage accents blend modern style with the best of a traditional bush safari camp. Designed by award-winning architects Silvio Rech and Lesley Carstens, the camp won Best New Property in Africa in 2014 and again in 2015. Its six spacious luxury safari villas (including a two-bedroom, two-bathroom family villa) rest beneath ancient msikizi trees. Each has a private plunge pool, a soaking tub with panoramic views over the river, and an open-plan design featuring canvas, timber, and reed accented with leather and raw linen. Each stretches out onto a shaded verandah where you can while away the afternoon or unwind with an in-villa spa treatment. Down a winding path, the main lodge beckons with a riverfront sun deck, an open-air library, a bar rich with old books and photographs, and a fire pit suspended high atop the river bank. Here, dining is a celebration of Zambian flavours enriched by produce grown in the camp's own garden.",
    heroImage: IMAGES.chinzombo,
    gallery: [IMAGES.southLuangwaSafari, IMAGES.southLuangwaElephant, IMAGES.southLuangwaLeopard],
    priceRange: "From $1,330 per person per night",
    roomTypes: ["Luxury Safari Villa", "Family Safari Villa (2BR, 2BA)"],
    amenities: [
      "Private plunge pool per villa",
      "Soaking tub with riverfront views",
      "Award-winning architectural design",
      "Morning and afternoon game drives",
      "Guided walking safaris",
      "Seasonal boat cruises",
      "Cultural village visits",
      "20-minute welcome massage included",
      "In-villa spa treatments",
      "Sleepout under the stars",
      "Riverfront dining and fire pit",
      "WiFi in villas",
      "Eco-cooled sleeping areas",
      "Full laundry and service included",
    ],
    rating: 4.9,
    reviews: [
      { name: "Zetta", text: "What an amazing, memory filled stay we enjoyed at Chinzombo. The accommodation and catering are next level. You will leave with a treasure trove of memories.", location: "Time+Tide Guest" },
      { name: "Robert and Catherine Thompson", text: "Chinzombo is a stunning lodge. The rooms are luxurious and spacious, with a deck and plunge pool overlooking the Luangwa River. Always an abundance of wildlife around the rooms.", location: "Toronto, Canada" },
    ],
    romanticHighlights: [
      "Private plunge pool overlooking the Luangwa River for two",
      "Sundowners around the riverfront fire pit at dusk",
      "In-villa spa treatments side by side",
      "Sleepout under the stars on a private platform",
      "Candlelit dinners grown from the camp's own garden",
    ],
  },
  {
    id: "puku-ridge-camp",
    name: "Puku Ridge Camp",
    destination: "south-luangwa",
    location: "South Luangwa National Park, Zambia",
    tagline: "Hilltop luxury with a front-row seat to the African wilderness",
    description:
      "Perched on an elevated ridge overlooking the Kakumbi Floodplain, Puku Ridge Camp offers eight air-conditioned luxury suites, each with its own plunge pool and star bed tower. An experience that brings you face to face with the wild.",
    longDescription:
      "Puku Ridge Camp occupies a spectacular hilltop position in the South Luangwa National Park, commanding panoramic views of the sprawling Kakumbi Floodplain below. Rebuilt in 2019, the camp's eight luxury tented suites are ranged across the hillside, each featuring a super-king or twin bed configuration, air conditioning (a rare and welcome luxury in the Luangwa Valley), and en-suite facilities with his-and-hers washbasins and a large bathtub with a view. Outside, a multi-level verandah with a private plunge pool overlooks the plains, while a tower above the bathroom offers a star bed for a night under the vast African sky. The main area features indoor and open-air lounges, a bar, a campfire, and a photographic hide overlooking a waterhole that draws predators and prey alike. Zambia is renowned for its walking safaris, and Puku Ridge's award-winning guides lead both vehicle and foot explorations, including night drives using an award-winning red-light protocol that allows guests to observe nocturnal predators undisturbed.",
    heroImage: IMAGES.pukuRidge,
    gallery: [IMAGES.southLuangwaSafari, IMAGES.southLuangwaElephant, IMAGES.southLuangwaLeopard],
    priceRange: "$800 to $1,500 per person per night",
    roomTypes: ["Luxury Safari Suite", "Premium Safari Suite"],
    amenities: [
      "Private plunge pool per suite",
      "Air conditioning (rare in the Luangwa Valley)",
      "Star bed tower for sleeping under the stars",
      "Morning and evening game drives",
      "Night drives with award-winning red-light protocol",
      "Guided walking safaris",
      "Photographic hide overlooking waterhole",
      "Bush dining under the stars",
      "Minibar with tea and coffee station",
      "Complimentary WiFi",
      "24/7 220V power with international charging",
      "Indoor and outdoor showers",
      "Campfire and open-air lounge",
    ],
    rating: 4.9,
    reviews: [
      { name: "Robert and Catherine Thompson", text: "The most incredible wildlife experience of our lives. We watched a leopard stalk from our plunge pool. Unforgettable.", location: "Toronto, Canada" },
      { name: "Guest, Puku Ridge", text: "A beautiful lodge with first-rate service and imaginative, well-presented food. Well designed and comfortable rooms with tremendous views.", location: "Chiawa Safaris Guest" },
    ],
    romanticHighlights: [
      "Sundowners on the ridge as the sun sets over the floodplain",
      "Private star bed sleepout for two beneath the Milky Way",
      "Bush dinners surrounded by lantern light with views of the waterhole",
      "Exclusive walking safaris for two with a private guide",
      "Wildlife viewing from your private plunge pool",
    ],
  },
  {
    id: "shawa-luangwa",
    name: "Shawa Luangwa Camp",
    destination: "south-luangwa",
    location: "Nsefu Sector, South Luangwa National Park, Zambia",
    tagline: "Intimate eco-luxury on the banks of the Luangwa River",
    description:
      "A small, eco-friendly bush camp overlooking the Luangwa River in the Nsefu Sector. Named after legendary Zambian guide Jacob Shawa, this intimate camp offers silent safaris in solar-powered electric vehicles and an immersion into one of the park's most untouched areas.",
    longDescription:
      "Shawa Luangwa Camp rests on the eastern bank of the Luangwa River, overlooking the sweeping landscape of the Nsefu Sector — one of the park's most pristine and wildlife-rich areas. Named in honour of Jacob Shawa, one of Zambia's most celebrated guides, the camp is a labour of love and a deep respect for the Luangwa Valley. The camp features just five raised A-line canvas tents on wooden platforms: three Luxury Couples Tents and one Family Tent (two tents connected by a deck). Each tent opens entirely on three sides to offer uninterrupted 270-degree views over the river and its pods of snorting hippo. Interiors feature a choice of twin or double beds, soft linen, a sunken bathtub, a private verandah, and a plunge pool. A starbed on the rooftop offers a place to sleep beneath the African sky. Shawa is a pioneer of silent safaris in South Luangwa, using solar-powered electric Land Cruisers that traverse the wilderness quietly with minimal carbon footprint. The main camp features an infinity pool, a fire pit at the edge of the wilderness, and a fully stocked bar where you can enjoy an armchair safari.",
    heroImage: IMAGES.shawaLuangwa,
    gallery: [IMAGES.southLuangwaSunset, IMAGES.southLuangwaSafari, IMAGES.southLuangwaElephant],
    priceRange: "From $500 per person per night",
    roomTypes: ["Luxury Couples Tent", "Family Tent (2 tents connected)"],
    amenities: [
      "Private plunge pool per tent",
      "Sunken bathtub with river views",
      "Silent safaris in solar-powered electric vehicles",
      "Morning and evening game drives",
      "Guided walking safaris",
      "Infinity pool overlooking the Luangwa River",
      "Starbed on rooftop for sleeping under the stars",
      "270-degree views from tent (opens on three sides)",
      "Campfire and fully stocked bar",
      "Eco-friendly design and operations",
      "Family tent configuration available",
      "Private dining on your deck available",
    ],
    rating: 4.8,
    reviews: [
      { name: "Guest, Shawa Luangwa", text: "A special little eco-camp in the vast wilderness. The silent safari vehicles are incredible — you can hear every sound of the bush. Jacob's legacy lives on here.", location: "Green Safaris Guest" },
      { name: "David and Claire Mueller", text: "An intimate, romantic escape. The tent opening onto the river with hippos grunting below was unforgettable.", location: "Berlin, Germany" },
    ],
    romanticHighlights: [
      "Private deck dining for two overlooking the Luangwa River",
      "Silent sunset safari drives with only the sounds of the bush",
      "Stargazing from your rooftop starbed",
      "Couples' bubble bath in a sunken tub with river views",
      "Lantern-lit dinners by the campfire at the water's edge",
    ],
  },
  {
    id: "luangwa-river-camp",
    name: "Luangwa River Camp",
    destination: "south-luangwa",
    location: "South Luangwa National Park, Zambia",
    tagline: "The rhythm of the river. The heart of the wild.",
    description:
      "Set along the banks of the Luangwa River beneath an ancient ebony grove, this intimate five-suite camp offers a classic safari experience with understated luxury and a profound connection to the wilderness. A romantic sanctuary for just ten guests.",
    longDescription:
      "Luangwa River Camp sits nestled under an ancient ebony grove on the banks of the Luangwa River in a game-rich area known as the Luangwa Wafwa. Operated by the renowned Robin Pope Safaris, this small and intimate camp offers just five thatched bush suites, ensuring a maximum of ten guests at any one time. Each suite is individually named (Mwala, Mazi, Merzi, Moto, and Ziko) and features a thatch-and-brick design with large sliding doors that open onto a private river-facing deck. The en-suite bathrooms boast double basins and a large sunken stone bathtub that gazes out onto your own private corner of Africa. A multi-level plunge pool with a cascading waterfall sits on the elevated river deck. The central guest area features an open-plan bar, lounge, and dining area surrounded by Balinese-inspired columns and a courtyard planted with banana trees. Cuisine is fresh and hearty, celebrating local Zambian produce, served by the river or in the communal boma. Activities include morning and afternoon game drives, guided walking safaris, night drives, and seasonal boat safaris on the Luangwa River.",
    heroImage: IMAGES.luangwaRiver,
    gallery: [IMAGES.southLuangwaSunset, IMAGES.southLuangwaLeopard, IMAGES.southLuangwaCamp],
    priceRange: "$520 to $950 per person per night",
    roomTypes: ["Bush Suite", "Premium River Suite"],
    amenities: [
      "River-facing deck with seating",
      "Sunken stone bathtub with river views",
      "Multi-level plunge pool with waterfall",
      "Morning and afternoon game drives",
      "Guided walking safaris with armed scouts",
      "Night drives for nocturnal wildlife",
      "Seasonal boat safaris on the Luangwa River",
      "Cultural village and school visits",
      "Wildlife Education Centre tour",
      "Stand-alone fans in suites",
      "Limited WiFi in communal areas",
      "Solar and battery-powered lighting",
      "Laundry and battery charging services",
      "Fresh, locally-sourced cuisine",
    ],
    rating: 4.8,
    reviews: [
      { name: "Sophie and Marc Leclerc", text: "Falling asleep to the sound of the river and waking to birdsong. We have never felt so connected to nature.", location: "Paris, France" },
      { name: "Guest, Luangwa River Camp", text: "First experience of LRC and not disappointed. The accommodation was lovely, very spacious and a high standard. The food, service and staff were all exceptional.", location: "Robin Pope Safaris Guest" },
    ],
    romanticHighlights: [
      "Riverfront dining by lantern light beneath the ebony trees",
      "Sundowners on your private deck as hippos surface in the river",
      "Private bush walks for two with an expert guide",
      "Stargazing from the plunge pool deck",
      "Intimate camp of just ten guests — your private corner of Africa",
    ],
  },
  {
    id: "xanadu-villas",
    name: "Xanadu Villas",
    destination: "zanzibar",
    location: "Kendwa, Zanzibar",
    tagline: "Where dreams meet the Indian Ocean",
    description:
      "Exquisite private villas on Zanzibar's northern coast, where turquoise waters kiss powder soft sand and every moment is designed for romance.",
    longDescription:
      "Xanadu Villas redefines barefoot luxury on the Spice Island. Set along the pristine coastline of Kendwa, these seven private villas are sanctuaries of space and light. Each villa features a private pool, an expansive terrace, and interiors that blend Swahili craftsmanship with contemporary elegance. Architecture is open and airy: sliding glass walls dissolve the boundary between inside and out, allowing the ocean breeze and the sound of waves to permeate every space. The resort's restaurant is one of Zanzibar's finest, serving seafood that arrives daily from local fishermen, paired with the island's abundant spices.",
    heroImage: IMAGES.xanadu,
    gallery: [IMAGES.zanzibarBeach, IMAGES.zanzibarAerial, IMAGES.zanzibarDhow],
    priceRange: "$700 to $1,400 per night",
    roomTypes: ["One Bedroom Villa", "Two Bedroom Villa", "Presidential Villa"],
    amenities: [
      "Private pool",
      "Direct beach access",
      "Restaurant and bar",
      "Spa and wellness center",
      "Water sports",
      "Butler service",
      "Private chef option",
      "Complimentary WiFi",
    ],
    rating: 4.9,
    reviews: [
      { name: "Jessica and Daniel Wright", text: "Xanadu is everything you imagine Zanzibar to be and more. Pure paradise. We are already planning our return.", location: "San Francisco, USA" },
    ],
    romanticHighlights: [
      "Private poolside dining under the stars",
      "Sunset dhow cruises with Champagne",
      "Couples spa rituals using Zanzibari spices",
      "Beachfront dinners with your toes in the sand",
    ],
  },
  {
    id: "zanzibar-white-sand-villas",
    name: "Zanzibar White Sand Villas",
    destination: "zanzibar",
    location: "Paje, Zanzibar",
    tagline: "White sand. Turquoise dreams. Endless romance.",
    description:
      "A collection of luxury villas on Zanzibar's breathtaking southeast coast, where the Indian Ocean lazes against endless white beaches beneath eternal sunshine.",
    longDescription:
      "Zanzibar White Sand Villas is an ode to the island's legendary coastline. Located on the powdery white sands of Paje, the resort offers 22 villas that blend Swahili architectural traditions with contemporary luxury. The villas are arranged around lush tropical gardens, each with a private pool and outdoor living area. The atmosphere is one of serene indulgence: yoga at sunrise, long walks on the beach, and long lunches at the ocean view restaurant. The beachfront infinity pool is the heart of the resort, a place where hours dissolve into golden days.",
    heroImage: IMAGES.whiteSand,
    gallery: [IMAGES.zanzibarAerial, IMAGES.zanzibarBeach, IMAGES.zanzibarDhow],
    priceRange: "$500 to $950 per night",
    roomTypes: ["Garden Villa", "Ocean View Villa", "Beachfront Villa"],
    amenities: [
      "Private pool",
      "Beachfront infinity pool",
      "Restaurant and bar",
      "Spa and wellness center",
      "Daily yoga pavilion",
      "Water sports",
      "Kite surfing school",
      "Complimentary WiFi",
    ],
    rating: 4.7,
    reviews: [
      { name: "Alex and Rachel Green", text: "The most beautiful beach we have ever seen. The villas are stunning and the service is impeccable.", location: "Melbourne, Australia" },
    ],
    romanticHighlights: [
      "Beachfront dinners as the sun sets over the Indian Ocean",
      "Couples yoga at sunrise",
      "Sunset beach walks on endless white sand",
      "Couples spa journeys",
    ],
  },
  {
    id: "the-residence-zanzibar",
    name: "The Residence Zanzibar",
    destination: "zanzibar",
    location: "Kizimkazi, Zanzibar",
    tagline: "Barefoot elegance on the Spice Island",
    description:
      "A stunning beachfront resort on Zanzibar's tranquil southern coast, where spacious villas, tropical gardens, and world class service create an unforgettable romantic escape.",
    longDescription:
      "The Residence Zanzibar is a haven of understated luxury on the island's tranquil southern coast. Set within 32 hectares of lush tropical gardens, the resort's 66 villas are among the most spacious in Zanzibar, each with a private pool, outdoor shower, and a terrace that opens onto the beach. The resort embodies quiet elegance: whitewashed walls, Swahili inspired architecture, and interiors that blend African textiles with contemporary design. The spa, set over water, offers treatments inspired by Zanzibar's spice heritage, while the resort's restaurants celebrate the island's culinary traditions with a modern, sophisticated twist.",
    heroImage: IMAGES.residence,
    gallery: [IMAGES.zanzibarSpa, IMAGES.zanzibarBeach, IMAGES.zanzibarAerial],
    priceRange: "$600 to $1,300 per night",
    roomTypes: ["Villa", "Premium Villa", "Beach Villa", "Presidential Villa"],
    amenities: [
      "Private pool",
      "Overwater spa",
      "Multiple restaurants",
      "Beach bar",
      "Tennis court",
      "Butler service",
      "Concierge",
      "Complimentary WiFi",
    ],
    rating: 4.8,
    reviews: [
      { name: "William and Elizabeth van der Merwe", text: "The Residence exceeded every expectation. The villa, the service, the spa. Perfection.", location: "Cape Town, South Africa" },
    ],
    romanticHighlights: [
      "Overwater spa treatments for two",
      "Private beach dinners with personal butler",
      "Sunset cocktails at the beach bar",
      "Couples spice ritual at the spa",
    ],
  },
];

export const PACKAGES = [
  {
    id: "honeymoon-escape",
    title: "Honeymoon Escape",
    subtitle: "Begin your forever in African paradise",
    description:
      "The ultimate romantic honeymoon weaving together the award-winning luxury of Time+Tide Chinzombo in South Luangwa with the pure relaxation of Zanzibar's pristine shores. A journey that celebrates your new beginning across Africa's most extraordinary landscapes.",
    duration: "10 nights",
    price: "$10,500 per couple",
    destinations: ["south-luangwa", "zanzibar"],
    properties: ["chinzombo", "xanadu-villas"],
    inclusions: [
      "All accommodation",
      "Domestic flights and private transfers",
      "Daily breakfast and dinner",
      "Safari game drives and walking safaris",
      "20-minute welcome massage at Chinzombo",
      "Private beach dinner in Zanzibar",
      "Couples spa treatment",
      "Honeymoon welcome amenity",
      "Personal concierge throughout your journey",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Lusaka", description: "Welcome at Kenneth Kaunda Airport. Private transfer to your hotel." },
      { day: 2, title: "Fly to South Luangwa", description: "Morning flight to Mfuwe. Transfer to Time+Tide Chinzombo. Afternoon game drive." },
      { day: 3, title: "Safari Immersion", description: "Full day of game drives and walking safaris with award-winning guides." },
      { day: 4, title: "Wilderness Romance", description: "Morning walking safari. Afternoon by your private plunge pool. In-villa spa treatment." },
      { day: 5, title: "Final Safari Morning", description: "Dawn game drive. Brunch. Flight to Zanzibar." },
      { day: 6, title: "Beach Arrival", description: "Arrive in Zanzibar. Transfer to Xanadu Villas. Welcome dinner." },
      { day: 7, title: "Ocean Bliss", description: "Day at leisure. Spa treatments. Pool. Beach." },
      { day: 8, title: "Spice Island Exploration", description: "Stone Town tour or spice plantation visit." },
      { day: 9, title: "Romantic Farewell", description: "Private beach dinner beneath the stars." },
      { day: 10, title: "Departure", description: "Transfer to Zanzibar Airport. Your journey becomes your most cherished memory." },
    ],
  },
  {
    id: "beach-bush-escape",
    title: "Beach and Bush Escape",
    subtitle: "The best of both African worlds",
    description:
      "Experience the contrasting wonders of Lake Malawi and South Luangwa. From the freshwater paradise of Africa's hidden beach escape to the raw wilderness of Zambia's premier safari destination, where silent electric vehicles glide through an untouched ecosystem. Two worlds. One extraordinary journey.",
    duration: "12 nights",
    price: "$8,500 per couple",
    destinations: ["lake-malawi", "south-luangwa"],
    properties: ["kaya-mawa", "shawa-luangwa"],
    inclusions: [
      "All accommodation",
      "Private transfers and flights",
      "Full board at all lodges",
      "Silent safaris in solar-powered electric vehicles",
      "Game drives and walking safaris",
      "All water sports equipment at Lake Malawi",
      "Private bush dinner",
      "Couples spa treatment",
      "24 hour concierge service",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Lilongwe", description: "Welcome. Overnight in Lilongwe." },
      { day: 2, title: "Lake Malawi Paradise", description: "Transfer to Kaya Mawa on Likoma Island." },
      { day: 3, title: "Island Life", description: "Kayaking, snorkeling, and island exploration." },
      { day: 4, title: "Lake Romance", description: "Private beach dinner. Sunset dhow cruise." },
      { day: 5, title: "Journey to the Bush", description: "Fly to Mfuwe. Transfer to Shawa Luangwa Camp." },
      { day: 6, title: "Safari Begins", description: "Silent game drive in electric vehicle. Walking safari." },
      { day: 7, title: "Wild Immersion", description: "Full day of safari activities. Sundowners by the river." },
      { day: 8, title: "Bush Luxury", description: "Relax by the infinity pool. Rooftop starbed. River views." },
      { day: 9, title: "Farewell Zambia", description: "Final game drive. Brunch. Departure." },
    ],
  },
  {
    id: "romantic-safari-journey",
    title: "Romantic Safari Journey",
    subtitle: "Intimate encounters with the wild",
    description:
      "An immersive safari experience designed exclusively for couples. Walk with wildlife on ancient paths, dine beneath the African sky, and sleep to the soundtrack of the bush. This is intimacy redefined.",
    duration: "7 nights",
    price: "$6,800 per couple",
    destinations: ["south-luangwa"],
    properties: ["puku-ridge-camp", "luangwa-river-camp"],
    inclusions: [
      "All accommodation",
      "All transfers",
      "Full board",
      "Private game vehicle",
      "Walking safaris",
      "Star bed experience",
      "Bush breakfast and dinner",
      "Photography guide",
    ],
    itinerary: [
      { day: 1, title: "Arrival", description: "Fly to Mfuwe. Transfer to Puku Ridge Camp." },
      { day: 2, title: "Safari Immersion", description: "Full day game drives and walking safaris." },
      { day: 3, title: "Bush Romance", description: "Private bush dinner under the stars." },
      { day: 4, title: "River Camp", description: "Transfer to Luangwa River Camp." },
      { day: 5, title: "River Life", description: "Game drives along the river. Sunset cruise." },
      { day: 6, title: "Star Bed Experience", description: "Sleep under the stars on a raised platform." },
      { day: 7, title: "Departure", description: "Final game drive. Brunch. Flight out." },
    ],
  },
  {
    id: "anniversary-escape",
    title: "Anniversary Escape",
    subtitle: "Celebrate your love story on the Spice Island",
    description:
      "A celebration of enduring love on the pristine shores of Zanzibar. From private dining on the sand to couples spa rituals, every moment honors your journey together.",
    duration: "7 nights",
    price: "$7,500 per couple",
    destinations: ["zanzibar"],
    properties: ["the-residence-zanzibar"],
    inclusions: [
      "Beach Villa accommodation",
      "Private transfers",
      "Daily breakfast",
      "Half board dining",
      "Couples spa ritual",
      "Private beach dinner",
      "Anniversary celebration package",
      "Personal butler",
    ],
    itinerary: [
      { day: 1, title: "Arrival", description: "Welcome at Zanzibar Airport. Transfer to The Residence." },
      { day: 2, title: "Beach Relaxation", description: "Day at leisure. Pool. Spa. Beach." },
      { day: 3, title: "Spice Tour", description: "Spice plantation visit. Lunch in Stone Town." },
      { day: 4, title: "Ocean Adventure", description: "Snorkeling and dhow sunset cruise." },
      { day: 5, title: "Wellness Day", description: "Couples spa treatments. Yoga. Relaxation." },
      { day: 6, title: "Romantic Dinner", description: "Private beach dinner to celebrate your love." },
      { day: 7, title: "Departure", description: "Breakfast. Transfer to airport." },
    ],
  },
  {
    id: "luxury-island-retreat",
    title: "Luxury Island Retreat",
    subtitle: "Your private island paradise on Lake Malawi",
    description:
      "An escape to the secluded shores of Lake Malawi. Stay at the iconic Kaya Mawa on Likoma Island and experience true barefoot luxury where the only schedule is the rhythm of the lake.",
    duration: "7 nights",
    price: "$6,200 per couple",
    destinations: ["lake-malawi"],
    properties: ["kaya-mawa"],
    inclusions: [
      "All accommodation",
      "Private transfers",
      "Full board",
      "Private dhow cruise",
      "Snorkeling equipment",
      "Couples massage",
      "Island picnic",
      "Concierge service",
    ],
    itinerary: [
      { day: 1, title: "Arrival", description: "Fly to Likoma Island. Settle into Kaya Mawa." },
      { day: 2, title: "Island Discovery", description: "Explore the island. Kayak. Swim." },
      { day: 3, title: "Lake Life", description: "Snorkeling. Sailing. Beach relaxation." },
      { day: 4, title: "Romance on the Lake", description: "Sunset dhow cruise. Private dinner." },
      { day: 5, title: "Adventure and Spa", description: "Water sports. Spa treatments." },
      { day: 6, title: "Island Farewell", description: "Final day. Stargazing." },
      { day: 7, title: "Departure", description: "Transfer to Lilongwe." },
    ],
  },
];

export const TESTIMONIALS = [
  {
    name: "Sarah and James Mitchell",
    location: "London, United Kingdom",
    text: "Kivara curated a honeymoon that exceeded every dream we held. From the moment we landed in Malawi to our final sunset in Zanzibar, every detail was flawless. This was not a trip. It was the beginning of our love story. We have never felt so seen, so cared for, so completely transported.",
    destination: "Lake Malawi and Zanzibar",
    rating: 5,
  },
  {
    name: "Emma and Thomas Chen",
    location: "Sydney, Australia",
    text: "We have traveled the world, but nothing compares to the raw beauty of South Luangwa experienced through Kivara's lens. Walking safaris at dawn. Sundowners on the riverbank. It was deeply moving in ways we struggle to articulate. This is Africa at its most beautiful.",
    destination: "South Luangwa",
    rating: 5,
  },
  {
    name: "Alexander and Natalia Petrov",
    location: "Oslo, Norway",
    text: "Kivara understood what we wanted before we knew it ourselves. The Zanzibar villa was breathtaking. The service impeccable. We felt like the only two people in the world. We are already planning our return.",
    destination: "Zanzibar",
    rating: 5,
  },
  {
    name: "Michael and Olivia Barnes",
    location: "New York, USA",
    text: "The Beach and Bush Escape was the perfect balance of adventure and romance. Swimming in Lake Malawi one day, tracking lions the next. Kivara's curation is nothing short of art. They do not plan trips. They compose journeys.",
    destination: "Lake Malawi and South Luangwa",
    rating: 5,
  },
];

export const EXPERIENCES = [
  {
    id: "private-beach-dining",
    title: "Private Beach Dining",
    description: "An intimate dinner beneath the stars with your toes in the sand. A table for two, candlelight, and the rhythm of waves as your soundtrack. The ultimate expression of romance.",
    image: IMAGES.dining,
    category: "Romance",
  },
  {
    id: "walking-safari",
    title: "Walking Safaris",
    description: "Follow in the footsteps of explorers on a guided walking safari. Feel the earth beneath your feet and connect with Africa on its own terms. There is no more intimate way to experience the wild.",
    image: IMAGES.walking,
    category: "Adventure",
  },
  {
    id: "sunset-dhow",
    title: "Sunset Dhow Cruises",
    description: "Sail into the golden hour on a traditional dhow. Champagne in hand, the sky painted in amber and rose. A moment you will carry in your heart forever.",
    image: IMAGES.dhow,
    category: "Romance",
  },
  {
    id: "couples-spa",
    title: "Couples Spa Rituals",
    description: "Side by side treatments in open air pavilions overlooking the ocean or bush. Ancient techniques meet modern wellness. Connection deepens with every breath.",
    image: IMAGES.spa,
    category: "Wellness",
  },
  {
    id: "star-bed",
    title: "Star Bed Safaris",
    description: "Sleep beneath a canopy of African stars on a raised platform in the wilderness. The ultimate romantic safari experience. You and the universe. Nothing between.",
    image: IMAGES.starbed,
    category: "Romance",
  },
  {
    id: "bush-dining",
    title: "Bush Dining",
    description: "A table set in the wilderness, surrounded by lanterns and the sounds of the African night. Fine dining meets raw nature. An evening you will never forget.",
    image: IMAGES.bushDining,
    category: "Dining",
  },
];

export const JOURNAL_POSTS = [
  {
    id: "honeymoon-guide-2026",
    title: "The Ultimate African Honeymoon Guide for Discerning Couples",
    excerpt: "From the shores of Lake Malawi to the wilds of Zambia and the spice scented breezes of Zanzibar. Discover the most romantic escapes Africa has to offer for those who refuse to compromise on beauty.",
    image: IMAGES.journalHoneymoon,
    category: "Honeymoon Guide",
    date: "May 10, 2026",
    author: "Kivara Concierge",
    readTime: "8 min read",
  },
  {
    id: "why-lake-malawi",
    title: "Why Lake Malawi is Africa's Most Coveted Luxury Secret",
    excerpt: "While the world flocks to the Mediterranean, a hidden paradise awaits on the shores of Lake Malawi. A place where luxury meets authenticity and romance finds its natural habitat.",
    image: IMAGES.journalMalawi,
    category: "Destination Feature",
    date: "April 28, 2026",
    author: "Kivara Concierge",
    readTime: "6 min read",
  },
  {
    id: "walking-safari-guide",
    title: "The Art of the Walking Safari: Intimacy with the Wild in South Luangwa",
    excerpt: "There is no more intimate way to experience Africa than on foot. Here is why South Luangwa is the world's premier walking safari destination for couples seeking transcendence.",
    image: IMAGES.journalWalking,
    category: "Safari Stories",
    date: "April 15, 2026",
    author: "Kivara Concierge",
    readTime: "10 min read",
  },
  {
    id: "zanzibar-spice-island",
    title: "Zanzibar: Love Letters from the Spice Island",
    excerpt: "Beyond the beaches lies an island woven with history, spice, and romance. Our guide to the most enchanting experiences in Zanzibar for couples who seek the extraordinary.",
    image: IMAGES.journalZanzibar,
    category: "Destination Feature",
    date: "March 30, 2026",
    author: "Kivara Concierge",
    readTime: "7 min read",
  },
];
