export const SITE_CONFIG = {
  name: "Trippa",
  tagline: "Luxury Beach & Bush Escapes Across Africa's Most Unforgettable Destinations",
  description:
    "Curated luxury African romance travel. Exquisite beach and bush escapes for couples seeking exclusivity, emotion, and modern African luxury.",
  url: "https://trippa.luxury",
  email: "concierge@trippa.luxury",
  phone: "+27 87 123 4567",
  whatsapp: "+27871234567",
  social: {
    instagram: "https://instagram.com/trippa",
    tiktok: "https://tiktok.com/@trippa",
    facebook: "https://facebook.com/trippa",
    pinterest: "https://pinterest.com/trippa",
  },
};

export const BRAND = {
  colors: {
    sand: "#D4C5A9",
    sandLight: "#E8DCC8",
    sandDark: "#B8A88A",
    warmWhite: "#F5F0EB",
    warmWhiteDark: "#EDE5DA",
    softBlack: "#1A1A1A",
    softBlackLight: "#2C2C2C",
    earth: "#8B7D6B",
    earthLight: "#A89880",
    gold: "#C9A96E",
    goldLight: "#D4BC8A",
    goldDark: "#B8944A",
    cream: "#FAF7F2",
  },
  fonts: {
    heading: "'Playfair Display', serif",
    body: "'Inter', sans-serif",
  },
};

export const DESTINATIONS = [
  {
    id: "lake-malawi",
    title: "Lake Malawi",
    subtitle: "Africa's Hidden Luxury Beach Escape",
    tagline: "Where freshwater meets paradise",
    description:
      "Discover the pristine shores of Lake Malawi, Africa's best-kept secret. Crystal-clear waters, golden beaches, and intimate lakeside lodges create the perfect setting for a romantic escape untouched by crowds.",
    heroVideo: "/videos/lake-malawi-hero.mp4",
    heroImage: "/images/lake-malawi-hero.jpg",
    slug: "lake-malawi",
    properties: ["kaya-mawa", "pumulani-lodge", "blue-zebra-island-lodge"],
    experiences: [
      "Private beach dining under the stars",
      "Sunset dhow cruises on the lake",
      "Snorkeling in crystal-clear waters",
      "Lake island picnics",
      "Kayaking at golden hour",
      "Local village cultural experiences",
    ],
    positioning:
      "Imagine a place where the lake stretches to the horizon like an ocean, where the pace of life slows to the rhythm of gentle waves. Lake Malawi offers the intimacy of a private paradise — exclusive, serene, and utterly romantic.",
  },
  {
    id: "south-luangwa",
    title: "South Luangwa",
    subtitle: "Raw Intimate Safari Luxury",
    tagline: "The birthplace of the walking safari",
    description:
      "South Luangwa National Park is the soul of African wilderness. Renowned as the birthplace of the walking safari, it offers an unfiltered connection with nature — intimate, raw, and breathtakingly beautiful.",
    heroVideo: "/videos/south-luangwa-hero.mp4",
    heroImage: "/images/south-luangwa-hero.jpg",
    slug: "south-luangwa",
    properties: ["puku-ridge-camp", "luangwa-safari-house", "luangwa-river-camp"],
    experiences: [
      "Guided walking safaris",
      "Night game drives with spotlights",
      "Sundowners on the riverbank",
      "Bush breakfasts in the wild",
      "Photography hides and blinds",
      "Stargazing in the African sky",
    ],
    positioning:
      "This is Africa as it once was — wild, untamed, and profoundly moving. South Luangwa offers an intimacy with the natural world that few places on earth can match. Here, luxury means waking to the sound of lions and dining under constellations.",
  },
  {
    id: "zanzibar",
    title: "Zanzibar",
    subtitle: "Tropical Romantic Elegance",
    tagline: "Where history meets crystalline waters",
    description:
      "Zanzibar — the Spice Island — where ancient Stone Town alleyways lead to pristine white-sand beaches. A tapestry of Swahili culture, turquoise waters, and world-class romance awaits.",
    heroVideo: "/videos/zanzibar-hero.mp4",
    heroImage: "/images/zanzibar-hero.jpg",
    slug: "zanzibar",
    properties: ["xanadu-villas", "zanzibar-white-sand-villas", "the-residence-zanzibar"],
    experiences: [
      "Spice plantation tours",
      "Stone Town heritage walks",
      "Private sandbank dining",
      "Sunset dhow cruises",
      "Couples spa rituals",
      "Deep-sea fishing excursions",
    ],
    positioning:
      "Zanzibar is a love letter to the senses. The scent of cloves in the air, the warmth of the Indian Ocean, the whispered history in Stone Town's ancient corridors — this island is made for romance.",
  },
];

export const PROPERTIES = [
  {
    id: "kaya-mawa",
    name: "Kaya Mawa",
    destination: "lake-malawi",
    location: "Likoma Island, Lake Malawi",
    tagline: "Barefoot luxury on a private island",
    description:
      "Perched on the shores of Likoma Island, Kaya Mawa is the epitome of barefoot luxury. Each suite is crafted from local stone and thatch, opening to panoramic views of Lake Malawi's crystalline waters. This is a place where time stands still.",
    longDescription:
      "Kaya Mawa is not merely a lodge — it's a sanctuary on one of Africa's most beautiful islands. Built into the rocky shoreline, each of the ten suites and villas offers complete privacy with sweeping lake views. The design philosophy is one of minimal intervention: local materials, handcrafted furnishings, and an architecture that lets the landscape take center stage. Days here unfold at nature's pace — swim in the infinity pool that seems to merge with the lake, explore hidden coves by kayak, or simply lose yourself in a book on your private deck. The restaurant serves farm-to-table cuisine with a Malawian soul, while the bar perches over the water for sundowners that linger into starlit evenings.",
    heroImage: "/images/kaya-mawa-hero.jpg",
    gallery: [
      "/images/kaya-mawa-1.jpg",
      "/images/kaya-mawa-2.jpg",
      "/images/kaya-mawa-3.jpg",
      "/images/kaya-mawa-4.jpg",
    ],
    priceRange: "$650 - $1,200 per night",
    roomTypes: ["Lake View Suite", "Beach Villa", "Island House"],
    amenities: [
      "Private infinity pool",
      "Overwater bar",
      "Farm-to-table restaurant",
      "Private beach",
      "Kayaking & water sports",
      "Spa treatments",
      "Helicopter pad",
      "WiFi",
    ],
    rating: 4.9,
    reviews: [
      {
        name: "Sarah & James",
        text: "The most romantic place we have ever stayed. Every detail was perfection.",
        location: "London, UK",
      },
      {
        name: "Emma & Thomas",
        text: "Kaya Mawa is pure magic. We arrived as guests and left as family.",
        location: "Sydney, Australia",
      },
    ],
    romanticHighlights: [
      "Private beach dinners",
      "Sunset dhow cruises",
      "Couples massage on the deck",
      "Stargazing from your suite",
    ],
  },
  {
    id: "pumulani-lodge",
    name: "Pumulani Lodge",
    destination: "lake-malawi",
    location: "Nankoma Peninsula, Lake Malawi",
    tagline: "Where the lake meets the sky",
    description:
      "Set on a private peninsula, Pumulani Lodge offers ten secluded villas with breathtaking views across Lake Malawi. It's a place of serene beauty and understated elegance.",
    longDescription:
      "Pumulani Lodge sits on a pristine peninsula, offering a level of seclusion that feels like your own private world. The ten villas are designed with a contemporary African aesthetic — clean lines, natural materials, and floor-to-ceiling windows that frame the lake like living art. Each villa has its own plunge pool and outdoor shower, creating an indoor-outdoor living experience that is both luxurious and deeply connected to nature. The main lodge features a stunning infinity pool, a library, and a dining room where the seasonal menu celebrates the flavors of Malawi.",
    heroImage: "/images/pumulani-hero.jpg",
    gallery: [
      "/images/pumulani-1.jpg",
      "/images/pumulani-2.jpg",
      "/images/pumulani-3.jpg",
    ],
    priceRange: "$550 - $1,000 per night",
    roomTypes: ["Lake View Villa", "Premium Villa", "Family Villa"],
    amenities: [
      "Private plunge pool",
      "Infinity pool",
      "Outdoor shower",
      "Restaurant & bar",
      "Water sports",
      "Spa",
      "Library",
      "WiFi",
    ],
    rating: 4.8,
    reviews: [
      {
        name: "Michael & Anna",
        text: "Paradise found. The villa, the views, the service — all extraordinary.",
        location: "New York, USA",
      },
    ],
    romanticHighlights: [
      "Private villa dining",
      "Couples spa journeys",
      "Sunset cruises",
      "Beach picnics",
    ],
  },
  {
    id: "blue-zebra-island-lodge",
    name: "Blue Zebra Island Lodge",
    destination: "lake-malawi",
    location: "Mumbo Island, Lake Malawi",
    tagline: "An island of your own",
    description:
      "Exclusively set on a private island, Blue Zebra Island Lodge offers an intimate escape with pristine beaches and some of the best snorkeling in Africa.",
    longDescription:
      "Blue Zebra Island Lodge occupies its own private island in the crystal-clear waters of Lake Malawi. With just ten rooms, the lodge offers an intimacy that is increasingly rare in travel. The island is a sanctuary for birdlife, and the surrounding waters are a haven for snorkelers and divers. Accommodation is understated and comfortable, with sustainability at the heart of the lodge's philosophy. Days are spent exploring the island, swimming in the lake, or simply relaxing in a hammock with the sound of lapping water.",
    heroImage: "/images/blue-zebra-hero.jpg",
    gallery: ["/images/blue-zebra-1.jpg", "/images/blue-zebra-2.jpg"],
    priceRange: "$400 - $750 per night",
    roomTypes: ["Island Room", "Lake Front Suite", "Private House"],
    amenities: [
      "Private island",
      "Snorkeling gear",
      "Restaurant & bar",
      "Beach loungers",
      "Bird watching",
      "Kayaking",
      "Sundeck",
    ],
    rating: 4.7,
    reviews: [
      {
        name: "David & Claire",
        text: "An island paradise. The snorkeling was world-class and the staff were incredible.",
        location: "Berlin, Germany",
      },
    ],
    romanticHighlights: [
      "Private island exploration",
      "Snorkeling for two",
      "Befront dining",
      "Sunset walks",
    ],
  },
  {
    id: "puku-ridge-camp",
    name: "Puku Ridge Camp",
    destination: "south-luangwa",
    location: "South Luangwa National Park, Zambia",
    tagline: "Safari luxury with a front-row seat to wilderness",
    description:
      "Perched on a ridge overlooking the Luangwa floodplain, Puku Ridge Camp offers an intimate safari experience with unparalleled game viewing from every suite.",
    longDescription:
      "Puku Ridge Camp is a masterclass in safari luxury. Perched on an elevated ridge, the camp commands sweeping views of the Luangwa floodplain — one of Africa's most prolific wildlife habitats. Seven expansive suites are designed for maximum immersion, with open-fronted designs that bring the wilderness to your doorstep. Each suite features a private plunge pool, indoor and outdoor showers, and a canopy bed that invites you to sleep under the African sky. The camp's location is legendary — during the dry season, wildlife concentrates along the river, offering exceptional sightings of leopard, lion, and the iconic Thornicroft's giraffe from the comfort of your deck.",
    heroImage: "/images/puku-ridge-hero.jpg",
    gallery: [
      "/images/puku-1.jpg",
      "/images/puku-2.jpg",
      "/images/puku-3.jpg",
    ],
    priceRange: "$800 - $1,500 per night",
    roomTypes: ["Safari Suite", "Premium Suite", "Family Suite"],
    amenities: [
      "Private plunge pool",
      "Game drives",
      "Walking safaris",
      "Bush dining",
      "Photography hide",
      "Spa treatments",
      "Star bed experience",
      "WiFi",
    ],
    rating: 4.9,
    reviews: [
      {
        name: "Robert & Catherine",
        text: "The most incredible wildlife experience of our lives. The camp is spectacular.",
        location: "Toronto, Canada",
      },
    ],
    romanticHighlights: [
      "Sundowners on the ridge",
      "Private bush dinners",
      "Star bed sleepouts",
      "Couples safari walks",
    ],
  },
  {
    id: "luangwa-safari-house",
    name: "Luangwa Safari House",
    destination: "south-luangwa",
    location: "South Luangwa National Park, Zambia",
    tagline: "Your private safari home",
    description:
      "An exclusive-use safari house set in a private game management area, offering the ultimate in privacy, space, and personalized wilderness experiences.",
    longDescription:
      "Luangwa Safari House is the ultimate expression of private safari luxury. This exclusive-use property sleeps up to eight guests in four en-suite bedrooms, each opening onto views of the pristine bushveld. The house is designed for convivial luxury — a great room with soaring thatch, a private pool, and an expansive deck where you can watch elephants wander past as you dine. With your own guide and vehicle, every day is your own: game drives at dawn, walking safaris, or simply hours spent reading by the pool. The house comes with a dedicated team including a chef, butler, and guide — your private bush support system.",
    heroImage: "/images/luangwa-house-hero.jpg",
    gallery: ["/images/luangwa-house-1.jpg", "/images/luangwa-house-2.jpg"],
    priceRange: "$2,000 - $4,000 per night (exclusive use)",
    roomTypes: ["Master Suite", "Guest Suite 1", "Guest Suite 2", "Guest Suite 3"],
    amenities: [
      "Private pool",
      "Exclusive vehicle & guide",
      "Personal chef",
      "Butler service",
      "Game drives",
      "Walking safaris",
      "Bush dining",
      "Full staff",
    ],
    rating: 5.0,
    reviews: [
      {
        name: "The Petersen Family",
        text: "An experience that bonded our family forever. The service was beyond anything we've experienced.",
        location: "Oslo, Norway",
      },
    ],
    romanticHighlights: [
      "Private house for two",
      "Candlelit bush dinners",
      "Private game drives",
      "Poolside stargazing",
    ],
  },
  {
    id: "luangwa-river-camp",
    name: "Luangwa River Camp",
    destination: "south-luangwa",
    location: "South Luangwa National Park, Zambia",
    tagline: "The rhythm of the river",
    description:
      "Set along the banks of the Luangwa River, this intimate camp offers a classic safari experience with modern luxury and a deep connection to the wild.",
    longDescription:
      "Luangwa River Camp captures the essence of a classic African safari. Set beneath a canopy of mahogany trees along the Luangwa River, the camp's ten tents are raised on wooden decks, each with a view of the river and the constant parade of wildlife it attracts. The design is understated luxury — canvas and timber, flowing mosquito nets, and indoor-outdoor bathrooms where you can shower under the stars. The camp's location is a wildlife corridor; hippos grunt in the river while elephants wander through camp. It is raw, authentic, and utterly captivating.",
    heroImage: "/images/luangwa-river-hero.jpg",
    gallery: ["/images/luangwa-river-1.jpg", "/images/luangwa-river-2.jpg"],
    priceRange: "$600 - $1,100 per night",
    roomTypes: ["River View Tent", "Premium Tent", "Family Tent"],
    amenities: [
      "River views",
      "Game drives",
      "Walking safaris",
      "Sundowner bar",
      "Bush breakfasts",
      "Photography",
      "Library",
      "WiFi",
    ],
    rating: 4.8,
    reviews: [
      {
        name: "Sophie & Marc",
        text: "Falling asleep to the sound of the river and waking to birdsong — pure magic.",
        location: "Paris, France",
      },
    ],
    romanticHighlights: [
      "Riverfront dining",
      "Sundowners by the water",
      "Bush walks for two",
      "Stargazing from your deck",
    ],
  },
  {
    id: "xanadu-villas",
    name: "Xanadu Villas",
    destination: "zanzibar",
    location: "Kendwa, Zanzibar",
    tagline: "Where dreams meet the Indian Ocean",
    description:
      "Exquisite private villas on Zanzibar's northern coast, where turquoise waters meet powder-soft sand and every moment is designed for romance.",
    longDescription:
      "Xanadu Villas redefines barefoot luxury on the spice island. Set along the pristine coastline of Kendwa, these seven private villas are sanctuaries of space and light. Each villa features a private pool, an expansive terrace, and interiors that blend Swahili craftsmanship with contemporary elegance. The architecture is open and airy — sliding glass walls dissolve the boundary between inside and out, allowing the ocean breeze and the sound of waves to permeate every space. The resort's restaurant is one of Zanzibar's finest, serving seafood that arrives daily from local fishermen, paired with the island's abundant spices.",
    heroImage: "/images/xanadu-hero.jpg",
    gallery: [
      "/images/xanadu-1.jpg",
      "/images/xanadu-2.jpg",
      "/images/xanadu-3.jpg",
    ],
    priceRange: "$700 - $1,400 per night",
    roomTypes: ["One-Bedroom Villa", "Two-Bedroom Villa", "Presidential Villa"],
    amenities: [
      "Private pool",
      "Beach access",
      "Restaurant & bar",
      "Spa",
      "Water sports",
      "Butler service",
      "Private chef option",
      "WiFi",
    ],
    rating: 4.9,
    reviews: [
      {
        name: "Jessica & Daniel",
        text: "Xanadu is everything you imagine Zanzibar to be — and more. Pure paradise.",
        location: "San Francisco, USA",
      },
    ],
    romanticHighlights: [
      "Private pool dining",
      "Sunset dhow cruises",
      "Couples spa rituals",
      "Beacront dinners",
    ],
  },
  {
    id: "zanzibar-white-sand-villas",
    name: "Zanzibar White Sand Villas",
    destination: "zanzibar",
    location: "Paje, Zanzibar",
    tagline: "White sand, turquoise dreams",
    description:
      "A collection of luxury villas on Zanzibar's breathtaking southeast coast, where the Indian Ocean lazes against endless white beaches.",
    longDescription:
      "Zanzibar White Sand Villas is an ode to the island's legendary coastline. Located on the powdery white sands of Paje, the resort offers 22 villas that blend traditional Swahili architecture with modern luxury. The villas are arranged around lush tropical gardens, each with a private pool and outdoor living area. The resort's atmosphere is one of serene indulgence — yoga at sunrise, long walks on the beach, and long lunches at the oceanview restaurant. The beachfront infinity pool is the heart of the resort, a place where hours dissolve into days.",
    heroImage: "/images/zanzibar-white-hero.jpg",
    gallery: [
      "/images/zanzibar-white-1.jpg",
      "/images/zanzibar-white-2.jpg",
    ],
    priceRange: "$500 - $950 per night",
    roomTypes: ["Garden Villa", "Ocean View Villa", "Beachfront Villa"],
    amenities: [
      "Private pool",
      "Beachfront infinity pool",
      "Restaurant & bar",
      "Spa & wellness",
      "Yoga pavilion",
      "Water sports",
      "Kite surfing",
      "WiFi",
    ],
    rating: 4.7,
    reviews: [
      {
        name: "Alex & Rachel",
        text: "The beach is the most beautiful we've ever seen. The villas are stunning.",
        location: "Melbourne, Australia",
      },
    ],
    romanticHighlights: [
      "Beacront dinners",
      "Couples yoga",
      "Sunset beach walks",
      "Spa journeys",
    ],
  },
  {
    id: "the-residence-zanzibar",
    name: "The Residence Zanzibar",
    destination: "zanzibar",
    location: "Kizimkazi, Zanzibar",
    tagline: "Barefoot elegance on the spice island",
    description:
      "A stunning beachfront resort on Zanzibar's southern coast, where spacious villas, tropical gardens, and world-class service create an unforgettable romantic escape.",
    longDescription:
      "The Residence Zanzibar is a haven of understated luxury on the island's tranquil southern coast. Set within 32 hectares of lush tropical gardens, the resort's 66 villas are among the most spacious in Zanzibar, each with a private pool, outdoor shower, and a terrace that opens onto the beach. The resort embodies a quiet elegance — whitewashed walls, Swahili-inspired architecture, and interiors that blend African textiles with contemporary design. The spa, set over water, offers treatments inspired by Zanzibar's spice heritage, while the resort's restaurants celebrate the island's culinary traditions with a modern twist.",
    heroImage: "/images/residence-zanzibar-hero.jpg",
    gallery: [
      "/images/residence-1.jpg",
      "/images/residence-2.jpg",
      "/images/residence-3.jpg",
    ],
    priceRange: "$600 - $1,300 per night",
    roomTypes: ["Villa", "Premium Villa", "Beach Villa", "Presidential Villa"],
    amenities: [
      "Private pool",
      "Overwater spa",
      "Multiple restaurants",
      "Beach bar",
      "Tennis court",
      "Kids club",
      "Butler service",
      "WiFi",
    ],
    rating: 4.8,
    reviews: [
      {
        name: "William & Elizabeth",
        text: "The Residence exceeded every expectation. The villa, the service, the spa — perfection.",
        location: "Cape Town, South Africa",
      },
    ],
    romanticHighlights: [
      "Overwater spa treatments",
      "Private beach dinners",
      "Sunset cocktails",
      "Couples spice rituals",
    ],
  },
];

export const PACKAGES = [
  {
    id: "honeymoon-escape",
    title: "Honeymoon Escape",
    subtitle: "Begin your forever in paradise",
    description:
      "The ultimate romantic honeymoon combining beach and bush. Start with the raw intimacy of a South Luangwa safari, then retreat to the pristine shores of Zanzibar for pure relaxation.",
    duration: "10 nights",
    price: "$8,500 per couple",
    destinations: ["south-luangwa", "zanzibar"],
    properties: ["puku-ridge-camp", "xanadu-villas"],
    inclusions: [
      "All accommodation",
      "Domestic flights and transfers",
      "Daily breakfast and dinner",
      "Safari game drives (shared)",
      "Private beach dinner",
      "Couples spa treatment",
      "Honeymoon welcome amenity",
      "Personal concierge",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Lusaka", description: "Welcome at Kenneth Kaunda Airport, private transfer to your hotel." },
      { day: 2, title: "Fly to South Luangwa", description: "Morning flight to Mfuwe, transfer to Puku Ridge Camp. Afternoon game drive." },
      { day: 3, title: "Safari Immersion", description: "Full day of game drives and walking safaris." },
      { day: 4, title: "Wilderness Romance", description: "Morning walk safari, afternoon at leisure, sundowner on the ridge." },
      { day: 5, title: "Final Safari Morning", description: "Dawn game drive, brunch, then flight to Zanzibar." },
      { day: 6, title: "Beach Arrival", description: "Arrive in Zanzibar, transfer to Xanadu Villas. Welcome dinner." },
      { day: 7, title: "Ocean Bliss", description: "Day at leisure. Spa treatments, pool, and beach." },
      { day: 8, title: "Spice Island Exploration", description: "Optional Stone Town tour or spice plantation visit." },
      { day: 9, title: "Romantic Farewell", description: "Private beach dinner under the stars." },
      { day: 10, title: "Departure", description: "Transfer to Zanzibar Airport for your onward journey." },
    ],
  },
  {
    id: "beach-bush-escape",
    title: "Beach & Bush Escape",
    subtitle: "The best of both worlds",
    description:
      "Experience the contrasting wonders of Lake Malawi and South Luangwa. From the freshwater paradise of Africa's hidden beach escape to the raw wilderness of Zambia's premier safari destination.",
    duration: "12 nights",
    price: "$9,200 per couple",
    destinations: ["lake-malawi", "south-luangwa"],
    properties: ["kaya-mawa", "luangwa-safari-house"],
    inclusions: [
      "All accommodation",
      "Private transfers and flights",
      "Full board at lodges",
      "Private game drives",
      "All water sports equipment",
      "Private bush dinner",
      "Couples spa treatment",
      "24/7 concierge",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Lilongwe", description: "Welcome and overnight in Lilongwe." },
      { day: 2, title: "Lake Malawi Paradise", description: "Transfer to Kaya Mawa on Likoma Island." },
      { day: 3, title: "Island Life", description: "Kayaking, snorkeling, and island exploration." },
      { day: 4, title: "Lake Romance", description: "Private beach dinner, sunset dhow cruise." },
      { day: 5, title: "Journey to the Bush", description: "Fly to Mfuwe, transfer to Luangwa Safari House." },
      { day: 6, title: "Safari Begins", description: "Game drives and walking safaris." },
      { day: 7, title: "Wild Immersion", description: "Full day of private safari activities." },
      { day: 8, title: "Bush Luxury", description: "Relax at the house, pool, reading, stargazing." },
      { day: 9, title: "Farewell Zambia", description: "Final game drive, brunch, departure." },
    ],
  },
  {
    id: "romantic-safari-journey",
    title: "Romantic Safari Journey",
    subtitle: "Intimate encounters with the wild",
    description:
      "An immersive safari experience designed for couples. Walk with wildlife, dine under the African sky, and sleep to the soundtrack of the bush.",
    duration: "7 nights",
    price: "$6,800 per couple",
    destinations: ["south-luangwa"],
    properties: ["puku-ridge-camp", "luangwa-river-camp"],
    inclusions: [
      "All accommodation",
      "All transfers",
      "Full board",
      "Private game vehicle",
      "Walking safaris",
      "Star bed experience",
      "Bush breakfast and dinner",
      "Photography guide",
    ],
    itinerary: [
      { day: 1, title: "Arrival", description: "Fly to Mfuwe, transfer to Puku Ridge Camp." },
      { day: 2, title: "Safari Immersion", description: "Full day game drives and walking." },
      { day: 3, title: "Bush Romance", description: "Private bush dinner under the stars." },
      { day: 4, title: "River Camp", description: "Transfer to Luangwa River Camp." },
      { day: 5, title: "River Life", description: "Game drives along the river, sunset cruise." },
      { day: 6, title: "Star Bed Experience", description: "Sleep under the stars on a raised platform." },
      { day: 7, title: "Departure", description: "Final game drive, brunch, flight out." },
    ],
  },
  {
    id: "anniversary-escape",
    title: "Anniversary Escape",
    subtitle: "Celebrate your love story",
    description:
      "A celebration of love on the pristine shores of Zanzibar. From private dining on the sand to couples spa rituals, every moment is designed to honor your journey together.",
    duration: "7 nights",
    price: "$7,500 per couple",
    destinations: ["zanzibar"],
    properties: ["the-residence-zanzibar"],
    inclusions: [
      "Accommodation in Beach Villa",
      "Private transfers",
      "Daily breakfast",
      "Half-board dining",
      "Couples spa ritual",
      "Private beach dinner",
      "Anniversary celebration package",
      "Personal butler",
    ],
    itinerary: [
      { day: 1, title: "Arrival", description: "Welcome at Zanzibar Airport, transfer to The Residence." },
      { day: 2, title: "Beach Relaxation", description: "Day at leisure. Pool, spa, and beach." },
      { day: 3, title: "Spice Tour", description: "Visit a spice plantation, lunch in Stone Town." },
      { day: 4, title: "Ocean Adventure", description: "Snorkeling and dhow sunset cruise." },
      { day: 5, title: "Wellness Day", description: "Couples spa treatments, yoga, relaxation." },
      { day: 6, title: "Romantic Dinner", description: "Private beach dinner to celebrate." },
      { day: 7, title: "Departure", description: "Breakfast, transfer to airport." },
    ],
  },
  {
    id: "luxury-island-retreat",
    title: "Luxury Island Retreat",
    subtitle: "Your private island paradise",
    description:
      "An escape to the secluded shores of Lake Malawi. Stay at the iconic Kaya Mawa on Likoma Island and experience true barefoot luxury.",
    duration: "7 nights",
    price: "$6,200 per couple",
    destinations: ["lake-malawi"],
    properties: ["kaya-mawa"],
    inclusions: [
      "All accommodation",
      "Private transfers",
      "Full board",
      "Private dhow cruise",
      "Snorkeling equipment",
      "Couples massage",
      "Island picnic",
      "Concierge service",
    ],
    itinerary: [
      { day: 1, title: "Arrival", description: "Fly to Likoma Island, settle into Kaya Mawa." },
      { day: 2, title: "Island Discovery", description: "Explore the island, kayak, swim." },
      { day: 3, title: "Lake Life", description: "Snorkeling, sailing, beach relaxation." },
      { day: 4, title: "Romance on the Lake", description: "Sunset dhow cruise, private dinner." },
      { day: 5, title: "Adventure & Spa", description: "Water sports, spa treatments." },
      { day: 6, title: "Island Farewell", description: "Final day on the island, stargazing." },
      { day: 7, title: "Departure", description: "Transfer to Lilongwe." },
    ],
  },
];

export const TESTIMONIALS = [
  {
    name: "Sarah & James Mitchell",
    location: "London, United Kingdom",
    text: "Trippa curated a honeymoon that exceeded every dream we had. From the moment we landed in Malawi to our final sunset in Zanzibar, every detail was flawless. This wasn't a trip — it was the beginning of our love story.",
    destination: "Lake Malawi & Zanzibar",
    rating: 5,
  },
  {
    name: "Emma & Thomas Chen",
    location: "Sydney, Australia",
    text: "We've traveled the world, but nothing compares to the raw beauty of South Luangwa experienced through Trippa's lens. Walking safaris at dawn, sundowners on the riverbank — it was deeply moving. This is Africa at its most beautiful.",
    destination: "South Luangwa",
    rating: 5,
  },
  {
    name: "Alexander & Natalia Petrov",
    location: "Oslo, Norway",
    text: "Trippa understood what we wanted before we knew it ourselves. The Zanzibar villa was breathtaking, the service impeccable. We felt like the only two people in the world. We are already planning our return.",
    destination: "Zanzibar",
    rating: 5,
  },
  {
    name: "Michael & Olivia Barnes",
    location: "New York, USA",
    text: "The Beach & Bush Escape was the perfect balance of adventure and romance. Swimming in Lake Malawi one day, tracking lions the next. Trippa's curation is nothing short of art.",
    destination: "Lake Malawi & South Luangwa",
    rating: 5,
  },
];

export const EXPERIENCES = [
  {
    id: "private-beach-dining",
    title: "Private Beach Dining",
    description: "An intimate dinner under the stars with your toes in the sand. A private table, candlelight, and the sound of waves as your soundtrack.",
    image: "/images/experience-dining.jpg",
    category: "Romance",
  },
  {
    id: "safari-walking",
    title: "Walking Safaris",
    description: "Follow in the footsteps of explorers on a guided walking safari. Feel the earth beneath your feet and connect with Africa on its own terms.",
    image: "/images/experience-walking.jpg",
    category: "Adventure",
  },
  {
    id: "sunset-dhow",
    title: "Sunset Dhow Cruises",
    description: "Sail into the golden hour on a traditional dhow. Champagne in hand, the sky painted in amber and rose — a moment you'll carry forever.",
    image: "/images/experience-dhow.jpg",
    category: "Romance",
  },
  {
    id: "couples-spa",
    title: "Couples Spa Rituals",
    description: "Side-by-side treatments in open-air pavilions overlooking the ocean or bush. Ancient techniques meet modern wellness.",
    image: "/images/experience-spa.jpg",
    category: "Wellness",
  },
  {
    id: "star-bed",
    title: "Star Bed Safaris",
    description: "Sleep under a canopy of African stars on a raised platform in the wilderness. The ultimate romantic safari experience.",
    image: "/images/experience-starbed.jpg",
    category: "Romance",
  },
  {
    id: "bush-dining",
    title: "Bush Dining",
    description: "A table set in the middle of the wilderness, surrounded by lanterns and the sounds of the African night. Fine dining meets raw nature.",
    image: "/images/experience-bushdining.jpg",
    category: "Dining",
  },
];

export const JOURNAL_POSTS = [
  {
    id: "honeymoon-guide-2026",
    title: "The Ultimate African Honeymoon Guide for 2026",
    excerpt: "From the shores of Lake Malawi to the wilds of Zambia and the spice-scented breezes of Zanzibar — discover the most romantic escapes Africa has to offer.",
    image: "/images/journal-honeymoon.jpg",
    category: "Honeymoon Guide",
    date: "May 10, 2026",
    author: "Trippa Concierge",
    readTime: "8 min read",
  },
  {
    id: "why-lake-malawi",
    title: "Why Lake Malawi is Africa's Best-Kept Luxury Secret",
    excerpt: "While the world flocks to the Mediterranean, a hidden paradise awaits on the shores of Lake Malawi — where luxury meets authenticity.",
    image: "/images/journal-lakemalawi.jpg",
    category: "Destination Feature",
    date: "April 28, 2026",
    author: "Trippa Concierge",
    readTime: "6 min read",
  },
  {
    id: "walking-safari-guide",
    title: "The Romance of Walking Safaris in South Luangwa",
    excerpt: "There is no more intimate way to experience Africa than on foot. Here's why South Luangwa is the world's premier walking safari destination.",
    image: "/images/journal-walking.jpg",
    category: "Safari Stories",
    date: "April 15, 2026",
    author: "Trippa Concierge",
    readTime: "10 min read",
  },
  {
    id: "zanzibar-spice-island",
    title: "Zanzibar: Love Letters from the Spice Island",
    excerpt: "Beyond the beaches lies an island woven with history, spice, and romance. Our guide to the most enchanting experiences in Zanzibar.",
    image: "/images/journal-zanzibar.jpg",
    category: "Destination Feature",
    date: "March 30, 2026",
    author: "Trippa Concierge",
    readTime: "7 min read",
  },
];
