-- Kivara Luxury Travel Platform - Agent Registry Persistence
-- Moves the Agent Registry governance ledger (Master OS §23 — AI Agent
-- Permissions) out of an in-memory const array into a Postgres table so the
-- full catalogue of Kivara AI agents is a source of truth shared across
-- processes and survives restarts. Additive and safe to apply against a
-- populated production database.
--
-- `name` is the natural primary key (each agent name is unique and stable);
-- registerAgent upserts on it, matching the previous module semantics.

-- ─── 1. agents table ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS agents (
  name TEXT PRIMARY KEY,
  department TEXT NOT NULL,
  objective TEXT NOT NULL,
  scope TEXT NOT NULL,
  tools TEXT[] NOT NULL DEFAULT '{}',
  knowledge TEXT[] NOT NULL DEFAULT '{}',
  permissions TEXT NOT NULL,
  output TEXT NOT NULL,
  escalation TEXT NOT NULL,
  success_metrics TEXT[] NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agents_department ON agents(department);

-- ─── 2. RLS (defence-in-depth; admin API uses service-role client) ────────
ALTER TABLE agents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Staff manage agents"
  ON agents FOR ALL USING (public.is_staff_user());

-- ─── 3. Seed: the full Kivara AI agent catalogue (previously KIVARA_AGENTS) ─
-- Idempotent via PRIMARY KEY (name) conflict.
INSERT INTO agents (name, department, objective, scope, tools, knowledge, permissions, output, escalation, success_metrics) VALUES
  -- Executive layer
  ('chief-of-staff', 'Executive',
   'Coordinate the Kivara AI organisation, maintain priorities, prepare daily briefings and weekly reviews, identify bottlenecks and route work to specialists or the founder.',
   'Reads platform-wide operational signals; prepares recommendations only — never executes consequential actions.',
   ARRAY['read_analytics','read_inquiries','read_bookings','read_finance','llm'],
   ARRAY['strategy','brand','commercial','operational'],
   'Read-only across all modules; recommend only.',
   'Daily briefing, weekly CEO review, bottleneck report, routing recommendations.',
   'Escalates every consequential decision to the founder (Human-in-the-Loop).',
   ARRAY['briefing accuracy','actionable recommendations','bottleneck detection rate']),
  -- Sales organisation
  ('receptionist', 'Sales',
   'First response — acknowledge inquiries promptly, warmly and on-brand.',
   'Acknowledge new inquiries; never qualifies or commits.',
   ARRAY['read_inquiries','send_email','llm'],
   ARRAY['brand'],
   'May send acknowledgement emails only.',
   'Acknowledgement message / email.',
   'Escalate to profiler once acknowledgement is handled.',
   ARRAY['response time','acknowledgement rate']),
  ('profiler', 'Sales',
   'Extract guest preferences, occasion, budget, destinations and travel style from an inquiry to build a guest profile.',
   'Qualify and profile the lead.',
   ARRAY['read_inquiries','read_knowledge','llm'],
   ARRAY['brand','destination','product'],
   'Read inquiries and knowledge; writes guest profile.',
   'ProfiledGuest with occasion, preferences, budget, dates, destinations.',
   'Escalate ambiguous/high-value leads to a human concierge.',
   ARRAY['profile completeness','accuracy']),
  ('curator', 'Product & Journey Design',
   'Design personal, emotional, luxurious, African, memorable and story-driven journeys rather than assembling hotel bookings.',
   'Journey concept → destination → experience → supplier matching → itinerary.',
   ARRAY['read_products','read_suppliers','read_knowledge','llm'],
   ARRAY['destination','product','brand'],
   'Recommend journeys and itineraries; no pricing commitments without approval.',
   'CuratedJourney with itinerary, highlights, destination selection.',
   'Escalate to quote-specialist for pricing and to founder for large commitments.',
   ARRAY['journey acceptance','guest satisfaction','romance standard']),
  ('quote-specialist', 'Sales',
   'Create a quote document with accurate pricing, margins, deposit and validity.',
   'Pricing + quote document generation from an approved journey.',
   ARRAY['read_products','read_finance','generate_document','llm'],
   ARRAY['commercial','pricing'],
   'Generate quotes within predefined margin rules; no discounts without approval.',
   'QuoteData + quote HTML.',
   'Escalate margin exceptions to the founder.',
   ARRAY['quote accuracy','no pricing invention']),
  ('payment-agent', 'Operations',
   'Handle payment links and receipt dispatch for bookings.',
   'Create payment links, confirm payments, send receipts.',
   ARRAY['read_bookings','read_finance','send_email','generate_document'],
   ARRAY['commercial','operational'],
   'Generate payment links and receipts for approved bookings only.',
   'Payment link, receipt document/email.',
   'Escalate unusual refunds or failed payment disputes to the founder.',
   ARRAY['payment completion','receipt accuracy']),
  ('itinerary-agent', 'Operations',
   'Finalise the itinerary and travel documentation for a confirmed journey.',
   'Itinerary verification, travel documents.',
   ARRAY['read_bookings','read_suppliers','generate_document'],
   ARRAY['operational','product'],
   'Finalise itineraries; confirm supplier bookings.',
   'Final itinerary, travel documents.',
   'Escalate feasibility problems to ops coordinator.',
   ARRAY['itinerary accuracy','document readiness']),
  ('reminder-agent', 'Operations',
   'Send pre-trip reminders (deposit, balance, documents, packing) on schedule.',
   'Scheduled reminders before travel start.',
   ARRAY['read_bookings','send_email','llm'],
   ARRAY['operational'],
   'Send scheduled reminder emails.',
   'Pre-trip reminder emails.',
   'Escalate payment/balance issues to payment-agent.',
   ARRAY['reminder delivery','on-time dispatch']),
  ('followup-agent', 'Sales',
   'Track unanswered enquiries, proposal status, objections and post-trip engagement; never spam.',
   'Follow-up cadence (d1/d7/d30) with calm, discreet, human tone.',
   ARRAY['read_inquiries','read_bookings','send_email','update_crm'],
   ARRAY['brand'],
   'Send scheduled follow-ups; log interactions.',
   'Follow-up emails + interaction log.',
   'Escalate hot leads and repeated non-response to a human.',
   ARRAY['response rate','conversion lift','no-spam compliance']),
  ('analyst', 'Strategy & Intelligence',
   'Provide funnel analytics and conversion insight.',
   'Sales funnel metrics.',
   ARRAY['read_analytics','read_inquiries','read_bookings','llm'],
   ARRAY['commercial'],
   'Read analytics; report only.',
   'Funnel metrics, conversion reports.',
   'Escalate anomalies to market-intelligence.',
   ARRAY['metric accuracy']),
  -- Strategy & Intelligence department (Master OS §5A)
  ('strategist', 'Strategy & Intelligence',
   'Maintain Kivara''s strategy, track objectives, opportunities and risks, and recommend actions.',
   'Strategic read of platform data; recommendations only.',
   ARRAY['read_analytics','read_inquiries','read_bookings','llm'],
   ARRAY['strategy','brand','commercial'],
   'Read-only; recommend only.',
   'Strategic brief.',
   'Escalate strategic decisions to the founder.',
   ARRAY['actionable strategy','objective tracking']),
  ('market-research', 'Strategy & Intelligence',
   'Analyse markets, identify emerging destinations and customer behaviour.',
   'Market intelligence over platform inquiry/booking data.',
   ARRAY['read_analytics','read_inquiries','read_bookings','llm'],
   ARRAY['destination','strategy'],
   'Read-only; research only.',
   'Market research brief.',
   'Escalate investment opportunities to the founder.',
   ARRAY['insight quality','emerging-destination detection']),
  ('competitor-intelligence', 'Strategy & Intelligence',
   'Analyse competitors and luxury travel trends.',
   'Competitive landscape; honest about placeholder data when live sources are unavailable.',
   ARRAY['llm','read_knowledge'],
   ARRAY['strategy','brand'],
   'Research only; never fabricate competitor facts.',
   'Competitive analysis brief.',
   'Escalate threats to the founder.',
   ARRAY['accuracy of claims']),
  ('opportunity-detection', 'Strategy & Intelligence',
   'Identify investment opportunities, threats and partnerships from platform data.',
   'Opportunity/threat detection.',
   ARRAY['read_analytics','read_inquiries','read_bookings','llm'],
   ARRAY['strategy','commercial'],
   'Read-only; recommend only.',
   'Opportunity and threat list.',
   'Escalate high-value opportunities to the founder.',
   ARRAY['opportunity discovery','risk flagging']),
  ('scenario-planning', 'Strategy & Intelligence',
   'Model base/upside/downside scenarios for planning decisions.',
   'Scenario modelling from current metrics.',
   ARRAY['read_analytics','read_bookings','llm'],
   ARRAY['strategy','commercial'],
   'Recommend scenarios; no commitments.',
   'Scenario plan.',
   'Escalate scenario-driven decisions to the founder.',
   ARRAY['scenario utility']),
  -- Romance intelligence (Master OS §6)
  ('romance-agent', 'Romance Intelligence',
   'Understand what emotional experience a couple is looking for and design the customer journey from Emotion → Story → Experience → Destination → Journey → Memory.',
   'Occasion detection, couple psychology, emotional journey design.',
   ARRAY['read_inquiries','read_knowledge','llm'],
   ARRAY['brand','destination','product'],
   'Recommend emotional journey concepts only.',
   'EmotionalProfile and emotion arc.',
   'Escalate delicate/sensitive occasions to a human.',
   ARRAY['emotional resonance','occasion accuracy']),
  ('relationship-agent', 'Sales',
   'Maintain customer relationship intelligence and ensure communication feels personal, calm, discreet, intelligent and human — never spam.',
   'Relationship memory and communication tone across all customer touchpoints.',
   ARRAY['read_guests','read_inquiries','read_bookings','update_crm'],
   ARRAY['brand','customer'],
   'Read/write CRM relationship notes; no unsolicited outreach.',
   'Relationship profile, communication guidance.',
   'Escalate relationship-risk customers to the founder.',
   ARRAY['personalisation','privacy compliance']),
  -- Operations organisation (Master OS §8)
  ('supplier-agent', 'Operations',
   'Match suppliers and services to a journey based on quality, availability and brand alignment — never merely the cheapest option.',
   'Supplier selection and coordination.',
   ARRAY['read_suppliers','read_bookings','llm'],
   ARRAY['supplier','operational'],
   'Recommend suppliers; no contractual commitments.',
   'Supplier recommendations and score.',
   'Escalate strategic supplier partnerships to the founder.',
   ARRAY['supplier score','booking success']),
  ('booking-coordinator', 'Operations',
   'Coordinate the journey from arrival → transfer → accommodation → experiences → activities → dining → safari → celebration → departure.',
   'Cross-supplier coordination for a single booking.',
   ARRAY['read_bookings','read_suppliers'],
   ARRAY['operational','supplier'],
   'Coordinate scheduled operations; confirm bookings.',
   'Ops plan, checklist, gaps, risks.',
   'Escalate feasibility gaps to ops coordinator/human.',
   ARRAY['seamless coordination','gap detection']),
  ('transfer-agent', 'Operations',
   'Confirm private transfers and ground/air connections match the itinerary.',
   'Transfer logistics for each journey leg.',
   ARRAY['read_bookings','read_suppliers'],
   ARRAY['operational','destination'],
   'Arrange transfers within approved supplier network.',
   'Transfer plan.',
   'Escalate connection risks to booking-coordinator.',
   ARRAY['on-time transfers']),
  ('accommodation-agent', 'Operations',
   'Match accommodation to guest preferences and budget.',
   'Accommodation selection within the journey.',
   ARRAY['read_products','read_suppliers','read_bookings'],
   ARRAY['product','supplier','destination'],
   'Recommend accommodation only.',
   'Accommodation recommendations.',
   'Escalate special accommodation requests to a human.',
   ARRAY['guest satisfaction with stays']),
  ('safari-ops', 'Operations',
   'Coordinate safari activities, guides and park logistics.',
   'Safari day logistics.',
   ARRAY['read_products','read_suppliers'],
   ARRAY['destination','operational'],
   'Coordinate scheduled safari activities.',
   'Safari activity plan.',
   'Escalate safety/weather risks to a human.',
   ARRAY['experience delivery']),
  ('activity-coordinator', 'Operations',
   'Coordinate experiences, activities and dining reservations.',
   'Per-activity booking and timing.',
   ARRAY['read_products','read_suppliers'],
   ARRAY['product','operational'],
   'Book activities within approved suppliers.',
   'Activity schedule.',
   'Escalate sold-out/conflict activities to a human.',
   ARRAY['activity fulfilment']),
  ('guest-experience', 'Operations',
   'Ensure the guest experience meets Kivara''s luxury and romance standards.',
   'Guest-facing quality and personalisation during the trip.',
   ARRAY['read_bookings','read_guests','llm'],
   ARRAY['brand','customer'],
   'Recommend experience enhancements.',
   'Guest-experience notes.',
   'Escalate service issues to a human immediately.',
   ARRAY['guest satisfaction','issue resolution time']),
  ('travel-docs', 'Operations',
   'Prepare travel documentation (visa, packing, insurance) for the journey.',
   'Travel documentation for the itinerary.',
   ARRAY['read_bookings','generate_document'],
   ARRAY['destination','operational'],
   'Generate travel documents from known data.',
   'Travel documents pack.',
   'Escalate visa/entry uncertainties to a human.',
   ARRAY['document completeness']),
  ('itinerary-verification', 'Operations',
   'Verify the itinerary is feasible and internally consistent.',
   'Schedules, transfers, timing, supplier availability.',
   ARRAY['read_bookings','read_suppliers'],
   ARRAY['operational'],
   'Flag inconsistencies; no changes without approval.',
   'Verification report.',
   'Escalate feasibility failures to booking-coordinator.',
   ARRAY['error-free itineraries']),
  ('emergency-coordinator', 'Operations',
   'Provide emergency coordination and contacts during travel.',
   'Emergency readiness and response.',
   ARRAY['read_bookings','read_suppliers'],
   ARRAY['operational','supplier'],
   'Surface emergency contacts and protocols only.',
   'Emergency contacts + protocol.',
   'Escalate any live emergency to a human immediately.',
   ARRAY['response readiness']),
  -- Quality control (Master OS §14)
  ('quality-control', 'Quality Control',
   'Check accuracy, commercial accuracy, operational feasibility, luxury standard, romance standard, brand consistency, risk and human-approval need for every important customer-facing output.',
   'Runs on proposals, quotes, journeys and customer communications.',
   ARRAY['llm','read_knowledge','read_finance','read_bookings'],
   ARRAY['brand','commercial','operational'],
   'Pass/warn/fail; may block release on fail.',
   'QcVerdict (pass/warn/fail + issues).',
   'Escalate fails to the responsible agent and founder if consequential.',
   ARRAY['caught errors','false-block rate']),
  -- Marketing organisation (Master OS §15)
  ('brand-strategist', 'Marketing',
   'Protect and advance the Kivara brand positioning as a trusted luxury journey curator.',
   'Brand voice, messaging and guardrails.',
   ARRAY['llm','read_knowledge'],
   ARRAY['brand'],
   'Recommend messaging; brand guardrails enforced.',
   'Brand guidance, guardrail verdicts.',
   'Escalate major brand decisions to the founder.',
   ARRAY['brand consistency']),
  ('content-agent', 'Marketing',
   'Produce content focused on emotion, stories, destinations, couples, Africa, romance, luxury, nature and discovery.',
   'Content briefs and drafts.',
   ARRAY['llm','read_knowledge','read_products'],
   ARRAY['brand','destination','product'],
   'Draft content; publish requires human approval.',
   'Content briefs and drafts.',
   'Escalate sensitive content to a human.',
   ARRAY['engagement','brand fit']),
  ('storytelling-agent', 'Marketing',
   'Craft Kivara love stories and emotional narrative angles.',
   'Story angles for guests, occasions and destinations.',
   ARRAY['llm','read_knowledge'],
   ARRAY['brand','destination'],
   'Draft storytelling; no claims beyond reality.',
   'Story angles.',
   'Escalate factual accuracy concerns to a human.',
   ARRAY['emotional resonance','shareability']),
  ('campaign-agent', 'Marketing',
   'Design campaigns that communicate Kivara curates African love stories, not trips.',
   'Campaign concept, audience, channels, message.',
   ARRAY['llm','read_knowledge','read_analytics','read_inquiries'],
   ARRAY['brand','strategy'],
   'Design campaigns; spend requires founder approval.',
   'Campaign plans.',
   'Escalate paid-media spend to the founder.',
   ARRAY['campaign ROI']),
  ('analytics-agent', 'Marketing',
   'Analyse marketing performance and guest acquisition.',
   'Channel and campaign performance.',
   ARRAY['read_analytics','read_inquiries','read_bookings','llm'],
   ARRAY['commercial'],
   'Read analytics; recommend.',
   'Marketing performance report.',
   'Escalate underperforming spend to the founder.',
   ARRAY['CAC trend','conversion attribution']),
  -- Distribution (Master OS §16)
  ('distribution-agent', 'Distribution',
   'Evaluate distribution channels by Reach + Customer quality + Acquisition cost + Commission + Brand fit + Conversion potential and recommend the best.',
   'Channel scoring and recommendation.',
   ARRAY['llm','read_analytics','read_inquiries'],
   ARRAY['strategy','commercial'],
   'Recommend channels; no contracts.',
   'Ranked channel recommendations.',
   'Escalate strategic distribution partnerships to the founder.',
   ARRAY['channel ROI','acquisition quality']),
  -- Partnership (Master OS §17)
  ('partnership-agent', 'Partnership',
   'Identify and prioritise partnerships that create long-term strategic advantage.',
   'Partner identification, scoring, prioritisation.',
   ARRAY['llm','read_knowledge','read_suppliers'],
   ARRAY['supplier','strategy','destination'],
   'Recommend partners; no commitments.',
   'Prioritised partner recommendations.',
   'Escalate strategic partnerships to the founder.',
   ARRAY['strategic advantage','partnership quality']),
  -- Finance & economics (Master OS §18)
  ('finance-economics', 'Finance & Economics',
   'Monitor revenue, gross/net margin, cash flow, supplier payments, deposits, outstanding balances, commissions, acquisition costs, average booking value, CLV, conversion and profitability by product and destination.',
   'Unit economics; never confusing revenue with profit.',
   ARRAY['read_finance','read_bookings','read_analytics'],
   ARRAY['commercial','pricing'],
   'Read-only; report only.',
   'Unit economics + profitability report.',
   'Escalate financial anomalies to the founder.',
   ARRAY['metric accuracy','profitability insight']),
  -- AI lab (Master OS §26)
  ('ai-lab', 'AI Lab',
   'Continuously discover new AI capabilities, models, automations, agent architectures, customer experiences, business models, distribution and revenue streams.',
   'Experimentation ledger and monthly review.',
   ARRAY['llm','read_knowledge'],
   ARRAY['strategy','brand'],
   'Recommend experiments; no production changes without approval.',
   'Experiment ledger, monthly prompt.',
   'Escalate promising experiments to the founder.',
   ARRAY['experiment throughput','adopted wins'])
ON CONFLICT (name) DO NOTHING;
